DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS replies;
DROP TABLE IF EXISTS outreach;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS companies;
